"""Retry and turn consistency invariants, each exercised by its own probe.

The ledger validates the retry policy the run pinned, permitted attempt order,
and the number of provider-reaching turns in addition to attempt indices and
summary arithmetic.

The probes edit rows produced through the shipped runner, reader and resume path:

1. A genuine three-attempt rate-limited turn shortened to two attempts, with
   every index, count, tally, measurement and total adjusted to agree.
2. A fourth attempt appended beyond the manifest's pinned three-attempt policy,
   with the same adjustments.
3. A genuine ``[fault, fault, response]`` turn reordered to
   ``[response, fault, fault]`` and renumbered, which no retry loop can produce
   because a response ends the turn.
4. One complete provider turn removed from a two-turn episode, with the episode
   and coverage summaries adjusted to match what was left.

Every row edited below is generated by the shipped runner and Anthropic adapter/SDK
against an in-process fake transport. No helper here produces both the
expected and the actual value, and no socket is opened.
"""

from __future__ import annotations

import dataclasses
import json
from decimal import Decimal
from pathlib import Path
from typing import Any

import pytest

from boundarybench.adapter import (
    PROVIDER_FAULT_AUTHENTICATION,
    PROVIDER_FAULT_RATE_LIMITED,
    TURN_END_BACKOFF_UNAFFORDABLE,
    TURN_END_COST_CAP_EXHAUSTED,
    TURN_END_DEADLINE_EXCEEDED,
    TURN_END_FAULT_NOT_RETRYABLE,
    TURN_END_PRE_DISPATCH_REFUSED,
    TURN_END_RESPONSE,
    TURN_END_RETRIES_EXHAUSTED,
    TURN_END_UNCLASSIFIED,
    TURN_TERMINAL_REASONS,
    AdapterError,
    PolicyFollowingFakeAdapter,
    ProviderTelemetry,
    fake_identity,
)
from boundarybench.ledger import (
    MEASUREMENT_PARTIAL,
    OUTCOME_COST_CAP_REACHED,
    OUTCOME_PROVIDER_FAILURE,
    OUTCOME_PROVIDER_RATE_LIMITED,
    OUTCOME_SUCCESS,
    LedgerError,
    _check_turn_sequence,
    read_ledger,
)
from boundarybench.runmanifest import MANIFEST_FILENAME, RunLimits, load_run_manifest
from tests.anthropic_transport import (
    RecordingTransport,
    error_body,
    message_body,
    tool_use_block,
)
from tests.test_cost_control_integrity import (
    _rate_limited_row,
    _reread,
    _resume,
    _rows,
    _write_rows,
)
from tests.test_provider_evidence_integrity import (
    LEDGER_FILENAME,
    PINNED_MODEL,
    anthropic_adapter,
    anthropic_manifest,
    build_manifest,
    execute,
    instant_retry,
    ledger_rows,
    ticking,
    variants,
)
from tests.test_runner_cost_control import SONNET, capped_run, first_request_reservation

RATE_LIMITED = (429, error_body("rate_limit_error", "slow down"))

READ_RECORDS = tool_use_block("read_records", {})


# -- the fixtures, asserted to be the evidence these probes claim to edit -----


def _turn(row: dict[str, Any], position: int = 0) -> dict[str, Any]:
    return row["provider_telemetry"]["turns"][position]


def _retally(row: dict[str, Any]) -> None:
    """Recompute every summary a coherent editor would recompute by hand.

    Deliberately *not* the production derivation: this is the attacker's side of
    each probe, making the edited row internally consistent. It recomputes only
    the totals — never the attempts or turns those totals summarise, which are
    what each probe edits.
    """
    telemetry = row["provider_telemetry"]
    turns = telemetry["turns"]
    for turn in turns:
        faults: dict[str, int] = {}
        for attempt in turn["attempts"]:
            if attempt["fault"] is not None:
                faults[attempt["fault"]] = faults.get(attempt["fault"], 0) + 1
        turn["attempt_count"] = len(turn["attempts"])
        turn["fault_counts"] = dict(sorted(faults.items()))
        turn["response_received"] = any(a["response_received"] for a in turn["attempts"])
        turn["usage_reported"] = any(a["usage_reported"] for a in turn["attempts"])
    episode_faults: dict[str, int] = {}
    for turn in turns:
        for fault, number in turn["fault_counts"].items():
            episode_faults[fault] = episode_faults.get(fault, 0) + number
    attempts = [attempt for turn in turns for attempt in turn["attempts"]]
    measured_turns = sum(1 for turn in turns if turn["turn_latency_seconds"] is not None)
    telemetry["attempt_count"] = len(attempts)
    telemetry["fault_counts"] = dict(sorted(episode_faults.items()))
    turns_used = row["turns_used"]
    status = (
        "unmeasured"
        if measured_turns == 0
        else ("full" if measured_turns == turns_used else MEASUREMENT_PARTIAL)
    )
    telemetry["measurement_status"] = status
    row["measurement"] = {
        "turns_total": turns_used,
        "turns_measured": measured_turns,
        "attempts_total": len(attempts),
        "attempts_measured": sum(
            1 for attempt in attempts if attempt["latency_seconds"] is not None
        ),
        "status": status,
    }
    row["cost_exposure_usd"] = float(
        sum(
            Decimal(attempt["cost_reservation_usd"])
            for attempt in attempts
            if attempt["cost_settlement"] == "forfeited"
        )
    )


def _answered_after_two_rate_limits(root: Path) -> list[dict[str, Any]]:
    """One real turn of ``[fault, fault, response]``, written by the real adapter."""
    capped_run(root, cap="100", steps=[RATE_LIMITED, RATE_LIMITED])
    rows = _rows(root)
    assert rows[0]["outcome"] == OUTCOME_SUCCESS
    outcomes = [attempt["outcome"] for attempt in _turn(rows[0])["attempts"]]
    assert outcomes == ["fault", "fault", "response"]
    return rows


def _two_turn_row(root: Path) -> list[dict[str, Any]]:
    """One real two-turn episode: the model reads, then completes the case."""
    capped_run(root, cap="100", steps=[message_body([READ_RECORDS], model=SONNET)])
    rows = _rows(root)
    assert rows[0]["turns_used"] == 2
    assert len(rows[0]["provider_telemetry"]["turns"]) == 2
    return rows


def test_the_rate_limited_fixture_is_a_genuine_three_attempt_turn(
    tmp_path: Path,
) -> None:
    """A negative probe against a row of the wrong shape would prove nothing."""
    rows = _rate_limited_row(tmp_path / "run")
    turn = _turn(rows[0])

    assert rows[0]["outcome"] == OUTCOME_PROVIDER_RATE_LIMITED
    assert turn["attempt_count"] == 3
    assert [attempt["index"] for attempt in turn["attempts"]] == [1, 2, 3]
    assert turn["terminal_reason"] == TURN_END_RETRIES_EXHAUSTED


def test_every_recorded_turn_states_a_reason_it_ended(tmp_path: Path) -> None:
    """The one field this fix adds, on real rows, from the closed set."""
    rows = _answered_after_two_rate_limits(tmp_path / "run")
    reasons = [
        turn["terminal_reason"]
        for row in rows
        for turn in row["provider_telemetry"]["turns"]
    ]

    assert reasons
    assert set(reasons) == {TURN_END_RESPONSE}
    for reason in reasons:
        assert reason in TURN_TERMINAL_REASONS


# -- 1. a turn may not record fewer attempts than the retries it ran ---------


def _shorten_to_two_attempts(rows: list[dict[str, Any]]) -> None:
    turn = _turn(rows[0])
    turn["attempts"] = turn["attempts"][:2]
    _retally(rows[0])


def test_a_three_attempt_turn_shortened_to_two_is_refused(tmp_path: Path) -> None:
    """A genuine three-failure turn edited to contain only two attempts.

    Every index, per-turn count, fault tally, episode tally, coverage summary
    and exposure total was adjusted to agree with the two attempts that were
    left, so the row followed from its own evidence — and a third of the run's
    real exposure had been dropped from the accounting. Nothing checked the
    attempts against the retry policy the manifest pins, or against the reason
    the turn recorded for stopping.
    """
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    reserved = first_request_reservation()
    assert rows[0]["cost_exposure_usd"] == float(reserved * 3)
    _shorten_to_two_attempts(rows)
    assert rows[0]["cost_exposure_usd"] == float(reserved * 2)
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "terminal_reason" in str(raised.value)


def test_a_three_attempt_turn_shortened_to_two_stops_the_resume(
    tmp_path: Path,
) -> None:
    """The same forgery through the production resume path, which spent again."""
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    _shorten_to_two_attempts(rows)
    _write_rows(root, rows)

    with pytest.raises(LedgerError):
        _resume(root)


# -- 2. a turn may not record more attempts than the policy permits ----------


def test_a_fourth_attempt_beyond_the_pinned_policy_is_refused(tmp_path: Path) -> None:
    """A fourth attempt appended under a pinned ``max_attempts`` of three.

    The appended attempt is a copy of a real one — same rederived reservation,
    same fault, same status — renumbered 4, with every summary and the exposure
    total adjusted. The run's own adapter could not have made it: the retry
    policy is inside adapter settings and therefore inside run identity, and it
    stops at three.
    """
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    turn = _turn(rows[0])
    fourth = json.loads(json.dumps(turn["attempts"][2]))
    fourth["index"] = 4
    turn["attempts"].append(fourth)
    _retally(rows[0])
    assert rows[0]["cost_exposure_usd"] == float(first_request_reservation() * 4)
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "max_attempts" in str(raised.value)


def test_a_fourth_attempt_beyond_the_pinned_policy_stops_the_resume(
    tmp_path: Path,
) -> None:
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    turn = _turn(rows[0])
    fourth = json.loads(json.dumps(turn["attempts"][2]))
    fourth["index"] = 4
    turn["attempts"].append(fourth)
    _retally(rows[0])
    _write_rows(root, rows)

    with pytest.raises(LedgerError):
        _resume(root)


# -- 3. a response ends the turn, so nothing follows it ----------------------


def _reorder_response_first(rows: list[dict[str, Any]]) -> None:
    turn = _turn(rows[0])
    attempts = turn["attempts"]
    reordered = [attempts[2], attempts[0], attempts[1]]
    for position, attempt in enumerate(reordered, start=1):
        attempt["index"] = position
    turn["attempts"] = reordered
    _retally(rows[0])


def test_a_response_reordered_before_later_attempts_is_refused(
    tmp_path: Path,
) -> None:
    """A ``[fault, fault, response]`` sequence rewritten as
    ``[response, fault, fault]`` and renumbered consecutively.

    Every summary survives the reordering untouched — the same three attempts,
    the same two faults, the same measured attempt, the same exposure — which is
    why arithmetic could not see it. The sequence is impossible all the same:
    the retry loop returns the moment a response arrives, so no attempt can
    follow one.
    """
    root = tmp_path / "run"
    rows = _answered_after_two_rate_limits(root)
    exposure = rows[0]["cost_exposure_usd"]
    _reorder_response_first(rows)
    assert rows[0]["cost_exposure_usd"] == exposure
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "response" in str(raised.value)


def test_a_response_reordered_before_later_attempts_stops_the_resume(
    tmp_path: Path,
) -> None:
    root = tmp_path / "run"
    rows = _answered_after_two_rate_limits(root)
    _reorder_response_first(rows)
    _write_rows(root, rows)

    with pytest.raises(LedgerError):
        _resume(root)


def test_a_turn_that_ended_in_a_fault_may_not_be_followed_by_another_turn(
    tmp_path: Path,
) -> None:
    """The episode-level half of the same rule, on an uncapped provider run.

    A turn that ended in anything but a response ended the episode with it, so
    it is the last turn there is. Swapping a genuine response turn and a genuine
    exhausted-retry turn leaves every count and tally identical and is refused
    on the order alone.
    """
    root = tmp_path / "run"
    manifest = anthropic_manifest(retry=instant_retry())
    transport = RecordingTransport(
        [message_body([READ_RECORDS], model=PINNED_MODEL)] + [(429, error_body())] * 3,
        default=message_body([READ_RECORDS], model=PINNED_MODEL),
    )
    execute(root, manifest, anthropic_adapter(transport.client(), retry=instant_retry()))
    rows = ledger_rows(root)
    turns = rows[0]["provider_telemetry"]["turns"]
    assert [turn["terminal_reason"] for turn in turns] == [
        TURN_END_RESPONSE,
        TURN_END_RETRIES_EXHAUSTED,
    ]

    turns[0], turns[1] = turns[1], turns[0]
    turns[0]["turn_index"], turns[1]["turn_index"] = (
        turns[1]["turn_index"],
        turns[0]["turn_index"],
    )
    path = root / LEDGER_FILENAME
    path.write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )

    with pytest.raises(LedgerError) as raised:
        read_ledger(path, manifest, variants())

    assert "response" in str(raised.value)


# -- 4. every provider-reaching turn of a capped run is accounted for --------


def _drop_the_second_turn(rows: list[dict[str, Any]]) -> None:
    telemetry = rows[0]["provider_telemetry"]
    telemetry["turns"] = telemetry["turns"][:1]
    _retally(rows[0])


def test_a_removed_provider_turn_is_refused(tmp_path: Path) -> None:
    """One of two provider turns deleted from the row.

    The episode still records the two turns it spent, and its trajectory still
    holds the two steps those turns produced; only the evidence of what the
    second turn asked of the provider is gone, with the episode tallies and the
    coverage summary adjusted to the partial measurement that leaves. A reader
    that only required turn indices to be sorted and unique had nothing to say
    about a turn that is simply absent.
    """
    root = tmp_path / "run"
    rows = _two_turn_row(root)
    _drop_the_second_turn(rows)
    assert rows[0]["measurement"]["status"] == MEASUREMENT_PARTIAL
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "turn" in str(raised.value)


def test_a_removed_provider_turn_stops_the_resume(tmp_path: Path) -> None:
    root = tmp_path / "run"
    rows = _two_turn_row(root)
    _drop_the_second_turn(rows)
    _write_rows(root, rows)

    with pytest.raises(LedgerError):
        _resume(root)


def test_a_capped_row_whose_telemetry_is_null_is_refused(tmp_path: Path) -> None:
    """The same removal, taken to its end: every turn's evidence deleted."""
    root = tmp_path / "run"
    rows = _two_turn_row(root)
    rows[0]["provider_telemetry"] = None
    rows[0]["measurement"] = {
        "turns_total": rows[0]["turns_used"],
        "turns_measured": 0,
        "attempts_total": None,
        "attempts_measured": None,
        "status": "unmeasured",
    }
    rows[0]["cost_exposure_usd"] = 0.0
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "turn" in str(raised.value)


# -- what the fix may not break ---------------------------------------------


def test_pre_dispatch_refusal_is_valid_before_first_or_later_retry_attempt() -> None:
    prior_retryable_attempt = {
        "outcome": "fault",
        "fault": PROVIDER_FAULT_RATE_LIMITED,
    }

    assert (
        _check_turn_sequence([], TURN_END_PRE_DISPATCH_REFUSED, 3, "test turn")
        == TURN_END_PRE_DISPATCH_REFUSED
    )
    assert (
        _check_turn_sequence(
            [prior_retryable_attempt],
            TURN_END_PRE_DISPATCH_REFUSED,
            3,
            "test turn",
        )
        == TURN_END_PRE_DISPATCH_REFUSED
    )


def test_an_honest_capped_run_still_reads_back(tmp_path: Path) -> None:
    """The rules are ones the real runner's own rows satisfy."""
    root = tmp_path / "run"
    _answered_after_two_rate_limits(root)
    assert len(_reread(root)) == 12


def test_an_honest_multi_turn_capped_run_still_reads_back(tmp_path: Path) -> None:
    root = tmp_path / "run"
    _two_turn_row(root)
    assert len(_reread(root)) == 12


def test_a_turn_stopped_early_by_the_cost_cap_reads_back(tmp_path: Path) -> None:
    """A retryable fault, one attempt of three, and a durable reason to stop.

    The cap is exactly one request's reservation, so the first attempt is
    authorised, its rate limit forfeits the whole reservation, and the retry the
    policy would otherwise permit cannot be authorised. That is legitimate
    behaviour and stays readable: the point of the closed reason set is to
    distinguish it from a turn whose attempts were deleted, not to ban it.
    """
    root = tmp_path / "run"
    capped_run(root, cap=str(first_request_reservation()), steps=[RATE_LIMITED])
    rows = _rows(root)
    turn = _turn(rows[0])

    assert rows[0]["outcome"] == OUTCOME_COST_CAP_REACHED
    assert turn["attempt_count"] == 1
    assert turn["terminal_reason"] == TURN_END_COST_CAP_EXHAUSTED
    assert len(_reread(root)) == len(rows)


def test_a_turn_that_never_got_a_request_away_reads_back(tmp_path: Path) -> None:
    """Zero attempts, a real turn, and the cap that stopped it before the first.

    The other end of the same legitimate ending: the run's first request was
    never affordable, so the turn honestly reports no attempts at all. Zero is
    an observation here and the reason it stopped is what says so.
    """
    root = tmp_path / "run"
    capped_run(root, cap="0.000001")
    rows = _rows(root)
    turn = _turn(rows[0])

    assert rows[0]["outcome"] == OUTCOME_COST_CAP_REACHED
    assert turn["attempt_count"] == 0
    assert turn["terminal_reason"] == TURN_END_COST_CAP_EXHAUSTED
    assert len(_reread(root)) == len(rows)


def test_a_turn_whose_budget_was_spent_before_a_request_reads_back(
    tmp_path: Path,
) -> None:
    """Zero attempts, honestly recorded, on a turn that ran out of wall clock."""
    root = tmp_path / "run"
    manifest = anthropic_manifest(
        retry=instant_retry(),
        limits=RunLimits(max_turns=12, max_messages=64, episode_timeout_seconds=1.0),
    )
    transport = RecordingTransport([], default=message_body([READ_RECORDS]))
    execute(
        root,
        manifest,
        anthropic_adapter(
            transport.client(), retry=instant_retry(), clock=ticking(100.0)
        ),
    )
    rows = ledger_rows(root)
    turn = rows[0]["provider_telemetry"]["turns"][0]

    assert rows[0]["outcome"] == OUTCOME_PROVIDER_FAILURE
    assert transport.calls == 0
    assert turn["attempt_count"] == 0
    assert turn["terminal_reason"] == TURN_END_DEADLINE_EXCEEDED
    assert read_ledger(root / LEDGER_FILENAME, manifest, variants())


def test_a_turn_abandoned_before_its_backoff_reads_back(tmp_path: Path) -> None:
    """One attempt, a retryable fault, and no budget left to wait and retry."""
    root = tmp_path / "run"
    manifest = anthropic_manifest(
        limits=RunLimits(max_turns=12, max_messages=64, episode_timeout_seconds=1.0)
    )
    transport = RecordingTransport(
        [(429, error_body())] * 12, default=message_body([READ_RECORDS])
    )
    execute(
        root,
        manifest,
        anthropic_adapter(transport.client(), clock=ticking(0.25)),
    )
    rows = ledger_rows(root)
    turn = rows[0]["provider_telemetry"]["turns"][0]

    assert rows[0]["outcome"] == OUTCOME_PROVIDER_RATE_LIMITED
    assert turn["attempt_count"] == 1
    assert turn["terminal_reason"] == TURN_END_BACKOFF_UNAFFORDABLE
    assert read_ledger(root / LEDGER_FILENAME, manifest, variants())


def test_a_fake_adapter_run_records_no_provider_telemetry_and_reads_back(
    tmp_path: Path,
) -> None:
    """The unmeasured semantics this fix must leave exactly alone.

    An in-process fake reaches no provider, so it reports no attempts, no turns
    and no reason any turn ended. ``null`` telemetry is that claim, and the
    exact per-turn accounting a real capped provider run is held to has nothing
    to account for here.
    """
    root = tmp_path / "run"
    identity = fake_identity()
    manifest = build_manifest(
        provider=identity.provider,
        model=identity.model,
        implementation=identity.implementation,
        adapter_version=identity.version,
        adapter_settings={},
    )
    execute(root, manifest, PolicyFollowingFakeAdapter(settings={}))
    rows = ledger_rows(root)

    assert rows
    for row in rows:
        assert row["provider_telemetry"] is None
        assert row["measurement"]["status"] == "unmeasured"
    assert len(read_ledger(root / LEDGER_FILENAME, manifest, variants())) == len(rows)


# -- the reason itself is evidence, and is checked like any other ------------


def test_a_row_without_a_terminal_reason_is_refused(tmp_path: Path) -> None:
    """Key-exact: a turn that does not say why it ended cannot be checked."""
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    _turn(rows[0]).pop("terminal_reason")
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "terminal_reason" in str(raised.value)


@pytest.mark.parametrize(
    "reason",
    ["gave up", "", TURN_END_RESPONSE, TURN_END_COST_CAP_EXHAUSTED, 3, None],
)
def test_a_terminal_reason_that_is_not_the_one_derivable_is_refused(
    tmp_path: Path, reason: Any
) -> None:
    """The genuine row's turn exhausted three retries, and says only that.

    A value outside the closed set, a value of the wrong type, and the two
    in-set values a shortened turn would need in order to look legitimate are
    all refused: with three attempts recorded against a three-attempt policy,
    exhaustion is the only state the turn can be in.
    """
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    _turn(rows[0])["terminal_reason"] = reason
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "terminal_reason" in str(raised.value)


def test_a_row_written_under_the_previous_schema_is_refused_by_version(
    tmp_path: Path,
) -> None:
    """A version-6 row states no reason any turn ended, so it is not re-judged."""
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    for row in rows:
        row["schema_version"] = 6
        for turn in row["provider_telemetry"]["turns"]:
            turn.pop("terminal_reason")
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert "schema_version" in str(raised.value)


# -- the policy the reader holds a row to is the run's own -------------------


def test_a_run_that_pins_no_retry_policy_cannot_bound_its_attempts(
    tmp_path: Path,
) -> None:
    """A row records attempts; the manifest declares nothing that bounds them.

    Refused rather than read under this build's default. How many attempts a
    turn was permitted is a result-affecting setting inside run identity, and a
    reader that filled it in for a run that does not state it would be checking
    the row against its own assumption.
    """
    root = tmp_path / "run"
    _rate_limited_row(root)
    manifest = load_run_manifest(root / MANIFEST_FILENAME)
    settings = {
        key: value for key, value in manifest.adapter_settings.items() if key != "retry"
    }

    with pytest.raises(LedgerError) as raised:
        read_ledger(
            root / LEDGER_FILENAME,
            dataclasses.replace(manifest, adapter_settings=settings),
            variants(),
        )

    assert "retry" in str(raised.value)


@pytest.mark.parametrize("pinned", [0, -1, "three", True, None, {"max_attempts": 3}])
def test_a_retry_bound_that_is_not_a_number_of_attempts_is_refused(
    tmp_path: Path, pinned: Any
) -> None:
    root = tmp_path / "run"
    _rate_limited_row(root)
    manifest = load_run_manifest(root / MANIFEST_FILENAME)
    settings = dict(manifest.adapter_settings)
    settings["retry"] = {**dict(settings["retry"]), "max_attempts": pinned}

    with pytest.raises(LedgerError) as raised:
        read_ledger(
            root / LEDGER_FILENAME,
            dataclasses.replace(manifest, adapter_settings=settings),
            variants(),
        )

    assert "max_attempts" in str(raised.value)


def test_a_turn_that_met_a_fault_worth_no_retry_reads_back(tmp_path: Path) -> None:
    """One attempt, a fault repeating cannot change, and no retry after it."""
    root = tmp_path / "run"
    capped_run(root, cap="100", steps=[(400, error_body("invalid_request_error", "no"))])
    rows = _rows(root)
    turn = _turn(rows[0])

    assert turn["attempt_count"] == 1
    assert turn["attempts"][0]["fault"] == "provider_request_rejected"
    assert turn["terminal_reason"] == TURN_END_FAULT_NOT_RETRYABLE
    assert len(_reread(root)) == len(rows)


def test_an_unclassifiable_attempt_ends_the_turn_it_was_made_in(
    tmp_path: Path,
) -> None:
    """An attempt whose answer this build cannot name is terminal, like a response.

    The request was made and may have been billed, so it is recorded rather than
    dropped — but naming a provider fault nobody observed would be a fabricated
    diagnosis, and there is nothing left to retry against. A row that records one
    and then claims its retry policy ran out is refused: exhaustion is a claim
    about three attempts that each met a retryable fault.
    """
    root = tmp_path / "run"
    rows = _rate_limited_row(root)
    last = _turn(rows[0])["attempts"][-1]
    last["outcome"] = "unclassified_error"
    last["fault"] = None
    last["http_status"] = None
    _retally(rows[0])
    _write_rows(root, rows)

    with pytest.raises(LedgerError) as raised:
        _reread(root)

    assert TURN_END_UNCLASSIFIED in str(raised.value)


# -- the contract's own two rules, stated where they are defined -------------


def test_a_telemetry_reason_outside_the_closed_set_cannot_be_constructed() -> None:
    """The writer is held to the same set the reader validates against."""
    with pytest.raises(ValueError) as raised:
        ProviderTelemetry(terminal_reason="gave up")

    assert "terminal_reason" not in str(raised.value)
    assert "gave up" in str(raised.value)


def test_the_integration_may_not_disagree_with_the_contract_on_retryability() -> None:
    """Whether repeating a fault can help is named once, in the contract.

    Two tables of the same fact drift, and the direction that matters is silent:
    a fault this integration retried and the ledger calls terminal would produce
    real rows the reader refuses.
    """
    from boundarybench.providers.anthropic_messages import _Fault

    with pytest.raises(AdapterError) as raised:
        _Fault(PROVIDER_FAULT_AUTHENTICATION, True, 401)

    assert "RETRYABLE_PROVIDER_FAULTS" in str(raised.value)
    assert _Fault(PROVIDER_FAULT_RATE_LIMITED, True, 429).retryable is True
